import React from 'react'

const Brands = () => {
  return (
    <div>
        
                      <div class="accordion-item">
                        <h2 class="accordion-header">
                          <button
                            class="accordion-button"
                            type="button"
                            data-bs-toggle="collapse"
                            data-bs-target="#panelsStayOpen-collapseTwo"
                            aria-expanded="false"
                            aria-controls="panelsStayOpen-collapseTwo"
                          >
                            Brand{" "}
                          </button>
                        </h2>
                        <div
                          id="panelsStayOpen-collapseTwo"
                          class="accordion-collapse collapse show"
                        >
                          <div class="accordion-body">
                            <ul class="collection-listing">
                              <li>
                                <div class="form-check">
                                  <input
                                    class="form-check-input"
                                    type="checkbox"
                                    value=""
                                    id="checkbox11"
                                  />
                                  <label
                                    class="form-check-label"
                                    for="checkbox11"
                                  >
                                    Samsung
                                  </label>
                                </div>
                              </li>
                              <li>
                                <div class="form-check">
                                  <input
                                    class="form-check-input"
                                    type="checkbox"
                                    value=""
                                    id="checkbox12"
                                  />
                                  <label
                                    class="form-check-label"
                                    for="checkbox12"
                                  >
                                    LG
                                  </label>
                                </div>
                              </li>
                              <li>
                                <div class="form-check">
                                  <input
                                    class="form-check-input"
                                    type="checkbox"
                                    value=""
                                    id="checkbox13"
                                  />
                                  <label
                                    class="form-check-label"
                                    for="checkbox13"
                                  >
                                    Onida
                                  </label>
                                </div>
                              </li>
                              <li>
                                <div class="form-check">
                                  <input
                                    class="form-check-input"
                                    type="checkbox"
                                    value=""
                                    id="checkbox14"
                                  />
                                  <label
                                    class="form-check-label"
                                    for="checkbox14"
                                  >
                                    Mitsubishi
                                  </label>
                                </div>
                              </li>
                              <li>
                                <div class="form-check">
                                  <input
                                    class="form-check-input"
                                    type="checkbox"
                                    value=""
                                    id="checkbox15"
                                  />
                                  <label
                                    class="form-check-label"
                                    for="checkbox15"
                                  >
                                    O General
                                  </label>
                                </div>
                              </li>
                              <li>
                                <div class="form-check">
                                  <input
                                    class="form-check-input"
                                    type="checkbox"
                                    value=""
                                    id="checkbox16"
                                  />
                                  <label
                                    class="form-check-label"
                                    for="checkbox16"
                                  >
                                    Bluestar
                                  </label>
                                </div>
                              </li>
                              <li>
                                <div class="form-check">
                                  <input
                                    class="form-check-input"
                                    type="checkbox"
                                    value=""
                                    id="checkbox17"
                                  />
                                  <label
                                    class="form-check-label"
                                    for="checkbox17"
                                  >
                                    Carrier
                                  </label>
                                </div>
                              </li>
                              <li>
                                <div class="form-check">
                                  <input
                                    class="form-check-input"
                                    type="checkbox"
                                    value=""
                                    id="checkbox18"
                                  />
                                  <label
                                    class="form-check-label"
                                    for="checkbox18"
                                  >
                                    Godrej
                                  </label>
                                </div>
                              </li>
                              <li>
                                <div class="form-check">
                                  <input
                                    class="form-check-input"
                                    type="checkbox"
                                    value=""
                                    id="checkbox19"
                                  />
                                  <label
                                    class="form-check-label"
                                    for="checkbox19"
                                  >
                                    Marque
                                  </label>
                                </div>
                              </li>
                              <li>
                                <div class="form-check">
                                  <input
                                    class="form-check-input"
                                    type="checkbox"
                                    value=""
                                    id="checkbox20"
                                  />
                                  <label
                                    class="form-check-label"
                                    for="checkbox20"
                                  >
                                    Midea
                                  </label>
                                </div>
                              </li>
                              <li>
                                <div class="form-check">
                                  <input
                                    class="form-check-input"
                                    type="checkbox"
                                    value=""
                                    id="checkbox21"
                                  />
                                  <label
                                    class="form-check-label"
                                    for="checkbox21"
                                  >
                                    Kelvinator
                                  </label>
                                </div>
                              </li>
                              <li>
                                <div class="form-check">
                                  <input
                                    class="form-check-input"
                                    type="checkbox"
                                    value=""
                                    id="checkbox22"
                                  />
                                  <label
                                    class="form-check-label"
                                    for="checkbox23"
                                  >
                                    Kenstar
                                  </label>
                                </div>
                              </li>
                              <li>
                                <div class="form-check">
                                  <input
                                    class="form-check-input"
                                    type="checkbox"
                                    value=""
                                    id="checkbox24"
                                  />
                                  <label
                                    class="form-check-label"
                                    for="checkbox25"
                                  >
                                    Hitachi
                                  </label>
                                </div>
                              </li>
                              <li>
                                <div class="form-check">
                                  <input
                                    class="form-check-input"
                                    type="checkbox"
                                    value=""
                                    id="checkbox26"
                                  />
                                  <label
                                    class="form-check-label"
                                    for="checkbox26"
                                  >
                                    Heir
                                  </label>
                                </div>
                              </li>
                              <li>
                                <div class="form-check">
                                  <input
                                    class="form-check-input"
                                    type="checkbox"
                                    value=""
                                    id="checkbox27"
                                  />
                                  <label
                                    class="form-check-label"
                                    for="checkbox27"
                                  >
                                    Whirlpool
                                  </label>
                                </div>
                              </li>
                              <li>
                                <div class="form-check">
                                  <input
                                    class="form-check-input"
                                    type="checkbox"
                                    value=""
                                    id="checkbox28"
                                  />
                                  <label
                                    class="form-check-label"
                                    for="checkbox28"
                                  >
                                    Voltas
                                  </label>
                                </div>
                              </li>
                              <li>
                                <div class="form-check">
                                  <input
                                    class="form-check-input"
                                    type="checkbox"
                                    value=""
                                    id="checkbox29"
                                  />
                                  <label
                                    class="form-check-label"
                                    for="checkbox29"
                                  >
                                    Amazon
                                  </label>
                                </div>
                              </li>
                              <li>
                                <div class="form-check">
                                  <input
                                    class="form-check-input"
                                    type="checkbox"
                                    value=""
                                    id="checkbox30"
                                  />
                                  <label
                                    class="form-check-label"
                                    for="checkbox30"
                                  >
                                    Sansui
                                  </label>
                                </div>
                              </li>
                              <li>
                                <div class="form-check">
                                  <input
                                    class="form-check-input"
                                    type="checkbox"
                                    value=""
                                    id="checkbox31"
                                  />
                                  <label
                                    class="form-check-label"
                                    for="checkbox31"
                                  >
                                    Toshiba
                                  </label>
                                </div>
                              </li>
                              <li>
                                <div class="form-check">
                                  <input
                                    class="form-check-input"
                                    type="checkbox"
                                    value=""
                                    id="checkbox32"
                                  />
                                  <label
                                    class="form-check-label"
                                    for="checkbox32"
                                  >
                                    Daikin
                                  </label>
                                </div>
                              </li>
                              <li>
                                <div class="form-check">
                                  <input
                                    class="form-check-input"
                                    type="checkbox"
                                    value=""
                                    id="checkbox33"
                                  />
                                  <label
                                    class="form-check-label"
                                    for="checkbox33"
                                  >
                                    Videocon
                                  </label>
                                </div>
                              </li>
                              <li>
                                <div class="form-check">
                                  <input
                                    class="form-check-input"
                                    type="checkbox"
                                    value=""
                                    id="checkbox34"
                                  />
                                  <label
                                    class="form-check-label"
                                    for="checkbox34"
                                  >
                                    Vestar
                                  </label>
                                </div>
                              </li>
                              <li>
                                <div class="form-check">
                                  <input
                                    class="form-check-input"
                                    type="checkbox"
                                    value=""
                                    id="checkbox35"
                                  />
                                  <label
                                    class="form-check-label"
                                    for="checkbox35"
                                  >
                                    Lloyd
                                  </label>
                                </div>
                              </li>
                              <li>
                                <div class="form-check">
                                  <input
                                    class="form-check-input"
                                    type="checkbox"
                                    value=""
                                    id="checkbox36"
                                  />
                                  <label
                                    class="form-check-label"
                                    for="checkbox36"
                                  >
                                    Panasonic
                                  </label>
                                </div>
                              </li>
                              <li>
                                <div class="form-check">
                                  <input
                                    class="form-check-input"
                                    type="checkbox"
                                    value=""
                                    id="checkbox37"
                                  />
                                  <label
                                    class="form-check-label"
                                    for="checkbox37"
                                  >
                                    Reconnect
                                  </label>
                                </div>
                              </li>
                              <li>
                                <div class="form-check">
                                  <input
                                    class="form-check-input"
                                    type="checkbox"
                                    value=""
                                    id="checkbox38"
                                  />
                                  <label
                                    class="form-check-label"
                                    for="checkbox38"
                                  >
                                    IFB
                                  </label>
                                </div>
                              </li>
                              <li>
                                <div class="form-check">
                                  <input
                                    class="form-check-input"
                                    type="checkbox"
                                    value=""
                                    id="checkbox39"
                                  />
                                  <label
                                    class="form-check-label"
                                    for="checkbox39"
                                  >
                                    Sanyo
                                  </label>
                                </div>
                              </li>
                              <li>
                                <div class="form-check">
                                  <input
                                    class="form-check-input"
                                    type="checkbox"
                                    value=""
                                    id="checkbox40"
                                  />
                                  <label
                                    class="form-check-label"
                                    for="checkbox40"
                                  >
                                    Trane
                                  </label>
                                </div>
                              </li>
                              <li>
                                <div class="form-check">
                                  <input
                                    class="form-check-input"
                                    type="checkbox"
                                    value=""
                                    id="checkbox41"
                                  />
                                  <label
                                    class="form-check-label"
                                    for="checkbox41"
                                  >
                                    Other
                                  </label>
                                </div>
                              </li>
                            </ul>
                          </div>
                        </div>
                      </div>

    </div>
  )
}

export default Brands
